### ISSUE TITLE
Data problem 

### ISSUE THREAD

**Issue by lyuchuny3** [gchaoxue/TD-LSTM#1]
Hi, I would like to run your lstm_demo.py
I have download "acl-14-short-data/train.raw" and "acl-14-short-data/test.raw",
however, I can't find the "embedding-results/sswe-h.txt",
could you give a link for this data? -- "embedding-results/sswe-h.txt"

Thanks

**Comment by gchaoxue** [comment]
SSWE is short for **Sentiment-Specific Word Embedding** which is introduced in one of Tang's paper [_Learning Sentiment-Specific Word Embedding for Twitter Sentiment Classification_](http://anthology.aclweb.org/P/P14/P14-1146.pdf).
You can download the sswe dataset from [there](http://ir.hit.edu.cn/~dytang/paper/sswe/embedding-results.zip), or you can easily find it from Tang's [homepage](http://ir.hit.edu.cn/~dytang/).
